name: Hello World
author: Chris McNutt
description: Description goes here.
inouts:
  who-to-greet:
    description: "Who to greet"
    required: true
    default: Chris
outputs:
  time:
    description: "The greeting time"
runs:
  using: "node12"
  main: "dist/index.js"
