name: CD
on:
  workflow_run:
    workflows: ["CI"]
    branches: ["main"]
    types:
      - completed
jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
      SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Use NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - name: Download Build Artifacts
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Zip Assets
        run: zip -r build.zip ./build
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Deploy Staging
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        run: npx surge --project ./build --domain zesty-elbow.surge.sh
      - name: Deploy Production
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx surge --project ./build --domain endurable-gold.surge.sh
      - name: Open Issue
        if: failure()
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Build failure for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_.",
            "assignees": ["${{ github.event.pull_request.user.login }}"]
            }'
