name: "Open Issue"
author: Chris McNutt
description: "Opens a GitHub issue"
inputs:
  token:
    description: "GitHub Token"
    required: true
  title:
    description: "Issue Title"
    required: true
  body:
    description: "Issue Body"
  assignees:
    description: "Issue Assignees"
outputs:
  issue: # id of output
    description: "The issue object a a json string"
runs:
  using: "node12"
  main: "dist/index.js"
